export default {
    "us": ["Appliances","Arts, Crafts & Sewing","Automotive","Baby","Beauty & Personal Care","Camera & Photo","Cell Phones & Accessories","Clothing, Shoes & Jewelry","Computers & Accessories","Electronics","Grocery & Gourmet Food","Health & Household","Home & Kitchen","Industrial & Scientific","Kitchen & Dining","Musical Instruments","Office Products","Patio, Lawn & Garden","Pet Supplies","Software","Sports & Outdoors","Tools & Home Improvement","Toys & Games","Video Games"],
    "de": ["Auto & Motorrad","Baby","Baumarkt","Beauty","Bekleidung","Beleuchtung","Bürobedarf & Schreibwaren","Computer & Zubehör","Drogerie & Körperpflege","Elektro-Großgeräte","Elektronik & Foto","Games","Garten","Gewerbe, Industrie & Wissenschaft","Haustier","Kamera & Foto","Koffer, Rucksäcke & Taschen","Küche, Haushalt & Wohnen","Lebensmittel & Getränke","Musikinstrumente & DJ-Equipment","Schmuck","Schuhe & Handtaschen","Spielzeug","Sport & Freizeit","Uhren"],
    "uk": ["Automotive","Baby Products","Beauty","Business, Industry & Science","Clothing","Computers & Accessories","DIY & Tools","Electronics & Photo","Garden & Outdoors","Grocery","Health & Personal Care","Home & Kitchen","Jewellery","Large Appliances","Lighting","Luggage","Musical Instruments & DJ","PC & Video Games","Pet Supplies","Shoes & Bags","Sports & Outdoors","Stationery & Office Supplies","Toys & Games","Watches"],
    "jp": ["DIY・工具・ガーデン","おもちゃ","シューズ&バッグ","ジュエリー","スポーツ&アウトドア","ドラッグストア","ビューティー","ベビー&マタニティ","ペット用品","ホビー","ホーム&キッチン","大型家電","家電&カメラ","文房具・オフィス用品","服&ファッション小物","産業・研究開発用品","腕時計","車&バイク","食品・飲料・お酒"],
    "fr": ["Animalerie","Auto & Moto","Bagages","Beauté & Parfum","Bijoux","Bricolage","Bébé & Puériculture","Chaussures & Sacs","Commerce, Industrie & Science","Cuisine & Maison","Epicerie","Fournitures de bureau","Gros électroménager","High-tech","Hygiène & Santé","Informatique","Instruments de musique & Sono","Jardin","Jeux & Jouets","Jeux vidéo","Logiciels","Luminaires & Eclairage","Montres","Sports & Loisirs","Vêtements"],
    "es": ["Bebé","Belleza","Bricolaje y herramientas","Coche y moto","Deportes y aire libre","Electrónica","Equipaje","Hogar y cocina","Iluminación","Industria, empresas y ciencia","Informática","Instrumentos musicales","Jardín","Joyería","Juguetes y juegos","Oficina y papelería","Relojes","Ropa","Salud y cuidado personal","Videojuegos","Zapatos y complementos"],
    "it": ["Abbigliamento","Alimentari e cura della casa","Auto e Moto","Bellezza","Casa e cucina","Commercio, Industria e Scienza","Elettronica","Fai da te","Giardino e giardinaggio","Giochi e giocattoli","Gioielli","Illuminazione","Informatica","Orologi","Prima infanzia","Salute e cura della persona","Scarpe e borse","Sport e tempo libero","Valigeria","Videogiochi"],
    "ca": ["Automotive","Baby","Beauty & Personal Care","Clothing & Accessories","Electronics","Grocery & Gourmet Food","Health & Personal Care","Industrial & Scientific","Jewelry","Luggage & Bags","Musical Instruments, Stage & Studio","Office Products","Patio, Lawn & Garden","Pet Supplies","Shoes & Handbags","Sports & Outdoors","Tools & Home Improvement","Toys & Games","Watches"],
    "mx": ["Bebé","Deportes y Aire Libre","Electrónicos","Herramientas y Mejoras del Hogar","Hogar y Cocina","Industria, Empresas y Ciencia","Instrumentos Musicales","Juguetes y Juegos","Libros","Música","Oficina y papelería","Ropa, Zapatos y Accesorios","Salud, Belleza y Cuidado Personal","Videojuegos"],
    "in": ["Baby","Baby Products","Bags, Wallets & Luggage","Beauty","Books","Car & Motorbike","Clothing & Accessories","Electronics","Gift Cards","Grocery & Gourmet Foods","Health & Personal Care","Home & Kitchen","Industrial & Scientific","Jewellery","Movies & TV Shows","Music","Musical Instruments","Office Products","Pet Supplies","Shoes & Handbags","Software","Sports, Fitness & Outdoors","Toys & Games","Video Games","Watches"],
}